version: '3.8'

services:
  postgres:
    container_name: vtal-boilerplate
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
