version: '3.8'

services:
  postgres:
    container_name: vtal-boilerplate
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
